# Configuration for MCP SSH Agent
IDLE_TIMEOUT = 0.5
BANNER_IDLE_TIMEOUT = 0.3
BANNER_TOTAL_TIMEOUT = 5.0
SELECT_TIMEOUT = 0.1
MAX_BUFFER_SIZE = 1_000_000
RECV_CHUNK_SIZE = 4096
SHELL_PROMPT_IDLE_TIMEOUT = 1.0
